/**
 * Fix Mode for Vibe Audit.
 *
 * Generates actionable fix prompts that can be:
 * 1. Saved as a .md file with all fixes organized by priority
 * 2. Output as individual prompts ready to paste into any AI tool
 * 3. Copied to clipboard (when available)
 *
 * Works with: Claude Code, Cursor, Lovable, Replit, Firebase Studio,
 * Google AI Studio, Base44, Canva Code, Bolt, v0, Windsurf
 */

import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { getFixPrompt } from './data/prompts.js';
import { bold, cyan, green, yellow, red, dim, gray } from './colors.js';

/**
 * Generate a fix report from findings.
 *
 * @param {import('./rules/types.js').Finding[]} findings
 * @param {string} targetDir
 * @param {'prompt' | 'file' | 'all'} mode
 */
export async function generateFixes(findings, targetDir, mode = 'all') {
  if (findings.length === 0) {
    console.log(green(bold('\n  ✅ No issues to fix. Ship it.\n')));
    return;
  }

  // Deduplicate by ruleId — one prompt per rule type, not per finding.
  const byRule = new Map();
  for (const f of findings) {
    if (!byRule.has(f.ruleId)) byRule.set(f.ruleId, []);
    byRule.get(f.ruleId).push(f);
  }

  if (mode === 'prompt' || mode === 'all') {
    printFixPrompts(byRule);
  }

  if (mode === 'file' || mode === 'all') {
    await writeFixFile(byRule, targetDir, findings.length);
  }
}

/**
 * Print fix prompts to terminal, one per rule.
 */
function printFixPrompts(byRule) {
  console.log('');
  console.log(bold('  ⚗️  FIX MODE — Copy-paste these into your AI coding tool'));
  console.log(dim('  ─────────────────────────────────────────────────────────'));
  console.log('');

  let index = 1;

  // Criticals first
  const critRules = [...byRule.entries()].filter(([, findings]) => findings[0].severity === 'critical');
  const warnRules = [...byRule.entries()].filter(([, findings]) => findings[0].severity === 'warning');
  const infoRules = [...byRule.entries()].filter(([, findings]) => findings[0].severity === 'info');

  if (critRules.length > 0) {
    console.log(red(bold('  🔴 CRITICAL — Fix these now\n')));
    for (const [ruleId, findings] of critRules) {
      printOnePrompt(index++, ruleId, findings);
    }
  }

  if (warnRules.length > 0) {
    console.log(yellow(bold('  🟡 WARNINGS — Fix before going live\n')));
    for (const [ruleId, findings] of warnRules) {
      printOnePrompt(index++, ruleId, findings);
    }
  }

  if (infoRules.length > 0) {
    console.log(cyan(bold('  ℹ️  INFO — Consider fixing\n')));
    for (const [ruleId, findings] of infoRules) {
      printOnePrompt(index++, ruleId, findings);
    }
  }
}

function printOnePrompt(index, ruleId, findings) {
  const promptData = getFixPrompt(ruleId);
  const files = [...new Set(findings.map(f => f.file))].join(', ');

  console.log(bold(`  ${index}. ${findings[0].ruleName}`));
  console.log(dim(`     ${findings.length} finding${findings.length > 1 ? 's' : ''} in: ${files}`));
  console.log('');

  if (promptData) {
    // Build a context-aware prompt with actual file names
    const contextPrompt = `${promptData.prompt}\n\nFiles to check: ${files}`;

    console.log(cyan('     ┌─ COPY THIS PROMPT ─────────────────────────────'));
    for (const line of contextPrompt.split('\n')) {
      console.log(cyan('     │ ') + line);
    }
    console.log(cyan('     └────────────────────────────────────────────────'));

    if (promptData.platformNotes) {
      console.log(dim(`     📋 ${promptData.platformNotes}`));
    }
  } else {
    console.log(gray(`     Fix: ${findings[0].fix}`));
  }

  console.log('');
}

/**
 * Write a VIBE-AUDIT-FIXES.md file with all prompts.
 */
async function writeFixFile(byRule, targetDir, totalFindings) {
  const lines = [
    '# ⚗️ Vibe Audit — Fix Guide',
    '',
    `> Generated by [vibe-audit](https://github.com/jackdog668/vibeaudit). ${totalFindings} issues found across ${byRule.size} rule categories.`,
    '',
    '**How to use:** Copy any prompt below and paste it into your AI coding tool (Claude Code, Cursor, Lovable, Replit, etc.).',
    '',
    '---',
    '',
  ];

  const critRules = [...byRule.entries()].filter(([, f]) => f[0].severity === 'critical');
  const warnRules = [...byRule.entries()].filter(([, f]) => f[0].severity === 'warning');
  const infoRules = [...byRule.entries()].filter(([, f]) => f[0].severity === 'info');

  let index = 1;

  if (critRules.length > 0) {
    lines.push('## 🔴 Critical — Fix These Now', '');
    for (const [ruleId, findings] of critRules) {
      writeOneSection(lines, index++, ruleId, findings);
    }
  }

  if (warnRules.length > 0) {
    lines.push('## 🟡 Warnings — Fix Before Going Live', '');
    for (const [ruleId, findings] of warnRules) {
      writeOneSection(lines, index++, ruleId, findings);
    }
  }

  if (infoRules.length > 0) {
    lines.push('## ℹ️ Info — Consider Fixing', '');
    for (const [ruleId, findings] of infoRules) {
      writeOneSection(lines, index++, ruleId, findings);
    }
  }

  lines.push('---', '', '*Built by [Digital Alchemy Academy](https://digitalalchemy.dev)*');

  const filePath = join(targetDir, 'VIBE-AUDIT-FIXES.md');
  await writeFile(filePath, lines.join('\n'));

  console.log('');
  console.log(green(bold(`  📄 Fix guide saved to: ${filePath}`)));
  console.log(dim('     Open it, copy the prompts, paste into your AI tool.'));
  console.log('');
}

function writeOneSection(lines, index, ruleId, findings) {
  const promptData = getFixPrompt(ruleId);
  const files = [...new Set(findings.map(f => f.file))];

  lines.push(`### ${index}. ${findings[0].ruleName}`);
  lines.push('');
  lines.push(`**${findings.length} finding${findings.length > 1 ? 's' : ''}** in: ${files.map(f => '`' + f + '`').join(', ')}`);
  lines.push('');

  // List each specific finding
  for (const f of findings) {
    lines.push(`- \`${f.file}${f.line ? ':' + f.line : ''}\` — ${f.message}`);
  }
  lines.push('');

  if (promptData) {
    const contextPrompt = `${promptData.prompt}\n\nFiles to check: ${files.join(', ')}`;
    lines.push('**Copy-paste this prompt into your AI coding tool:**');
    lines.push('');
    lines.push('```');
    lines.push(contextPrompt);
    lines.push('```');

    if (promptData.platformNotes) {
      lines.push('');
      lines.push(`> **Platform notes:** ${promptData.platformNotes}`);
    }
  } else {
    lines.push(`**Fix:** ${findings[0].fix}`);
  }

  lines.push('');
  lines.push('---');
  lines.push('');
}
